In [1]:
from tensorflow.keras.preprocessing.text import one_hot

s:\Krish_Naik_GenAI\Udemy_labs\RNN_End2End_Project\venv\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [2]:
sent = [
    "the glass of milk",
    "the glass of juice",
    "the cup of tea",
    "I am a good boy",
    "I am a good developer",
    "understand the meaning of words",
    "your videos are good"
]


In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# Define the Vocubulary size

voc_size = 10000

In [5]:
# One hot representation with every word
one_hot_repr = [one_hot(words,voc_size) for words in sent]

In [6]:
one_hot_repr

[[8192, 6608, 960, 9079],
 [8192, 6608, 960, 503],
 [8192, 3284, 960, 3191],
 [3738, 9617, 5236, 4461, 8328],
 [3738, 9617, 5236, 4461, 3610],
 [6004, 8192, 1016, 960, 348],
 [9710, 5181, 5489, 4461]]

In [7]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [8]:
import numpy as np


In [9]:
sent_length = 8
embeded_docs = pad_sequences(one_hot_repr,padding='post',maxlen=sent_length) # Zeros will be added to the end
# embeded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embeded_docs)

[[8192 6608  960 9079    0    0    0    0]
 [8192 6608  960  503    0    0    0    0]
 [8192 3284  960 3191    0    0    0    0]
 [3738 9617 5236 4461 8328    0    0    0]
 [3738 9617 5236 4461 3610    0    0    0]
 [6004 8192 1016  960  348    0    0    0]
 [9710 5181 5489 4461    0    0    0    0]]


In [10]:
# Feature representation
dim =10


In [11]:
# create embedding layer

# model = Sequential()
# model.add(Embedding(voc_size,dim,sent_length))
# model.compile('adam','mse') # Krish naik, following is GPT one..
#---
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Input

model = Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size, dim))

model.compile(optimizer='adam', loss='mse')



In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embeded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step


array([[[-1.13686547e-02,  2.01153271e-02,  3.70837338e-02,
          2.83586122e-02,  3.85575928e-02,  1.07624754e-02,
         -3.41530927e-02,  9.25139338e-03,  1.73375271e-02,
         -1.03348009e-02],
        [-4.25787568e-02, -6.00869581e-03, -4.43226583e-02,
         -3.79654057e-02, -3.95939127e-02, -9.16711241e-03,
          3.46791781e-02,  4.38630469e-02,  2.37202384e-02,
         -1.96850430e-02],
        [-3.35456133e-02,  4.22051288e-02, -3.92002948e-02,
          2.87975110e-02,  2.22426169e-02, -3.56756076e-02,
         -3.71899009e-02,  1.61010362e-02,  1.96239091e-02,
         -3.08653712e-02],
        [ 2.71046422e-02, -1.48795471e-02,  4.29395549e-02,
          1.22284666e-02, -3.63785625e-02, -6.36943430e-03,
          4.42512073e-02,  4.68638428e-02,  8.76188278e-06,
          2.76446342e-03],
        [-2.70902757e-02,  4.24149297e-02,  2.38390826e-02,
         -6.10319525e-03,  7.37094879e-03, -3.92300710e-02,
         -1.08207390e-03,  4.42456044e-02, -2.650334

In [14]:
embeded_docs[0]

array([8192, 6608,  960, 9079,    0,    0,    0,    0], dtype=int32)

In [15]:
# model.predict(embeded_docs[0][0])
import numpy as np
model.predict(np.expand_dims(embeded_docs[0], axis=0))
# model.predict([embeded_docs[0]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step


array([[[-1.1368655e-02,  2.0115327e-02,  3.7083734e-02,  2.8358612e-02,
          3.8557593e-02,  1.0762475e-02, -3.4153093e-02,  9.2513934e-03,
          1.7337527e-02, -1.0334801e-02],
        [-4.2578757e-02, -6.0086958e-03, -4.4322658e-02, -3.7965406e-02,
         -3.9593913e-02, -9.1671124e-03,  3.4679178e-02,  4.3863047e-02,
          2.3720238e-02, -1.9685043e-02],
        [-3.3545613e-02,  4.2205129e-02, -3.9200295e-02,  2.8797511e-02,
          2.2242617e-02, -3.5675608e-02, -3.7189901e-02,  1.6101036e-02,
          1.9623909e-02, -3.0865371e-02],
        [ 2.7104642e-02, -1.4879547e-02,  4.2939555e-02,  1.2228467e-02,
         -3.6378562e-02, -6.3694343e-03,  4.4251207e-02,  4.6863843e-02,
          8.7618828e-06,  2.7644634e-03],
        [-2.7090276e-02,  4.2414930e-02,  2.3839083e-02, -6.1031953e-03,
          7.3709488e-03, -3.9230071e-02, -1.0820739e-03,  4.4245604e-02,
         -2.6503349e-02, -1.8326320e-02],
        [-2.7090276e-02,  4.2414930e-02,  2.3839083e-02, -6.